from __future__ import annotations

from .modular_sampling import cartesian_power_tuples, sample_modular_points
from .random_sections import RandomSectionWitness, find_random_section_wit
from .real_fallbacks import (
    CoordinateBounds,
    FallbackAttempt,
    FallbackInstanceResult,
    LinearEliminationResult,
    MethodSearchResult,
    algebraic_variables,
    as_rational_if_exact,
    coordinate_bounds,
    could_be_zero,
    eliminate_linear_equations,
    expand_with_subs,
    fast_factor_list,
    find_nonzero_polynomial_witness,
    find_real_witnesses,
    formula_to_rule_sets,
    is_algebraic_condition,
    is_bounded_solution_set,
    is_rational_number,
    is_reliably_zero,
    is_valid_numeric_value,
    normalize_relation,
    normalize_relations,
    rational_bound,
    sample_bounded_witnesses,
    sample_section_witnesses,
    satisfies_formula,
    solve_univar_witness,
    sort_conditions,
    to_dnf_formula,
    try_fast_witness,
    try_methods,
    vector_relations,
)
from .rule_extension import PartialAssignExtension, complete_partial_assign, extend_partial_cons
from .witness_generation import VariableDomainSpec, sample_free_assignments

__all__ = [
    "CoordinateBounds",
    "cartesian_power_tuples",
    "FallbackAttempt",
    "FallbackInstanceResult",
    "LinearEliminationResult",
    "MethodSearchResult",
    "PartialAssignExtension",
    "RandomSectionWitness",
    "VariableDomainSpec",
    "algebraic_variables",
    "as_rational_if_exact",
    "satisfies_formula",
    "complete_partial_assign",
    "could_be_zero",
    "rational_bound",
    "eliminate_linear_equations",
    "coordinate_bounds",
    "expand_with_subs",
    "extend_partial_cons",
    "fast_factor_list",
    "find_nonzero_polynomial_witness",
    "find_random_section_wit",
    "find_real_witnesses",
    "solve_univar_witness",
    "formula_to_rule_sets",
    "is_algebraic_condition",
    "is_rational_number",
    "is_reliably_zero",
    "is_valid_numeric_value",
    "normalize_relation",
    "normalize_relations",
    "is_bounded_solution_set",
    "try_fast_witness",
    "try_methods",
    "sample_bounded_witnesses",
    "sample_free_assignments",
    "sample_modular_points",
    "sample_section_witnesses",
    "sort_conditions",
    "to_dnf_formula",
    "vector_relations",
]
