"""Experimental integer and modular solving helpers.

These routines are not part of the certified real-CAD core and may return
experimental or fragment-specific results.
"""

from .congruence import (
    ModularSolveResult,
    combine_mod_crt,
    eliminate_one_var,
    find_modular_instance,
    find_quant_free_mod_inst,
    norm_mod_form,
    rec_solve_basis,
    simp_mod_ineqs,
    solve_mod_lin_sys,
    solve_mod_poly_sys,
    solve_modular_system,
    solve_quant_free_mod_sys,
    solve_quant_mod_sys,
)
from .diophantine import (
    IntEqnSolveResult,
    detect_binary_homog_eqn,
    detect_int_lin_elim,
    detect_sum_eqn,
    reduce_int_divis,
    solve_binary_eqn,
    solve_int_branches,
    solve_int_divis,
    solve_int_fams2,
    solve_int_methods,
    solve_int_pruning,
    solve_int_recursion2,
    solve_int_sys_via_factor,
    solve_sum_of_two_squares,
)
from .engine import (
    IntegerSolveRequest,
    IntSolverRegistration,
    default_int_registry,
    run_int_solver_pipeline,
)
from .factorization import (
    FactorizationAnalysis,
    IntegerFactorBranch,
    enum_factor_branches,
    factor_thread_eqn,
    norm_factor_int_eqn,
    solve_int_recursion,
)
from .families import (
    IntegerFamilyTag,
    detect_binary_homog_fam,
    detect_int_problem_fam,
    detect_sum_fam,
)
from .groebner_recursion import (
    GroebnerRecursiveStep,
    GroebnerTriangAnalysis,
    analyze_groebner_struct,
    compute_groebner_basis,
    extract_lin_basis,
    find_int_recursion,
    rec_reduce_sys,
    recon_int_sol_fams,
)
from .linear_divisibility import (
    LinDivisReduction,
    apply_lin_reduction,
    detect_lin_reduction,
)
from .linear_recursion import (
    IntLinElimCand,
    apply_int_lin_elim,
    choose_best_int_lin_elim,
    enum_int_lin_elim_cands,
    find_int_recursion2,
    rec_reduce_int_lin_sys,
)
from .modular_quantifier_elimination import (
    ModularQePlan,
    ModularQeResult,
    ModularQuantifierBlock,
    build_modular_qe_plan,
    eliminate_mod_form,
    eliminate_quant_m,
    norm_mod_quant_blocks,
    simp_proj_mod_form,
    solve_mod_qe_with_blocks,
    solve_quant_decomp,
)
from .output_normalization import (
    CanonIntSolveResult,
    canon_int_result,
    dedup_int_points,
    finite_points_to_formula,
)
from .special_families import (
    SpecialFamDesc,
    detect_diag_fam,
    detect_pell_family,
    detect_pythag_fam,
    detect_sum_fam2,
    detect_two_cubes_family,
    pythag_triple_form,
    solve_binary_scan,
    solve_diag_fam,
    solve_int_fams,
    solve_pell_family,
    solve_pythag_triples_fam,
    solve_sum_of_squares_fam,
    solve_two_cubes_family,
)
from .thue import (
    ThueFamilyDescriptor,
    detect_binary_fam,
    solve_binary_bounded,
    solve_binary_lll,
)

EXPERIMENTAL = True

__all__ = [
    "ModularSolveResult",
    "norm_mod_form",
    "combine_mod_crt",
    "simp_mod_ineqs",
    "solve_mod_lin_sys",
    "solve_mod_poly_sys",
    "rec_solve_basis",
    "solve_quant_free_mod_sys",
    "find_quant_free_mod_inst",
    "eliminate_one_var",
    "solve_quant_mod_sys",
    "solve_modular_system",
    "find_modular_instance",
    "LinDivisReduction",
    "detect_lin_reduction",
    "apply_lin_reduction",
    "IntEqnSolveResult",
    "detect_int_lin_elim",
    "reduce_int_divis",
    "solve_int_divis",
    "solve_int_branches",
    "solve_int_sys_via_factor",
    "solve_int_recursion2",
    "solve_int_pruning",
    "detect_sum_eqn",
    "solve_sum_of_two_squares",
    "detect_binary_homog_eqn",
    "solve_binary_eqn",
    "solve_int_methods",
    "CanonIntSolveResult",
    "dedup_int_points",
    "finite_points_to_formula",
    "canon_int_result",
    "IntegerFamilyTag",
    "detect_sum_fam",
    "detect_binary_homog_fam",
    "detect_int_problem_fam",
    "ThueFamilyDescriptor",
    "detect_binary_fam",
    "solve_binary_bounded",
    "IntegerSolveRequest",
    "IntSolverRegistration",
    "default_int_registry",
    "run_int_solver_pipeline",
    "IntLinElimCand",
    "enum_int_lin_elim_cands",
    "choose_best_int_lin_elim",
    "apply_int_lin_elim",
    "rec_reduce_int_lin_sys",
    "find_int_recursion2",
    "IntegerFactorBranch",
    "FactorizationAnalysis",
    "norm_factor_int_eqn",
    "enum_factor_branches",
    "factor_thread_eqn",
    "solve_int_recursion",
    "GroebnerRecursiveStep",
    "GroebnerTriangAnalysis",
    "compute_groebner_basis",
    "analyze_groebner_struct",
    "recon_int_sol_fams",
    "rec_reduce_sys",
    "find_int_recursion",
    "solve_binary_lll",
    "detect_pell_family",
    "solve_pell_family",
    "ModularQuantifierBlock",
    "ModularQeResult",
    "norm_mod_quant_blocks",
    "solve_mod_qe_with_blocks",
    "eliminate_mod_form",
    "ModularQePlan",
    "build_modular_qe_plan",
    "simp_proj_mod_form",
    "solve_quant_decomp",
    "eliminate_quant_m",
    "solve_int_fams2",
    "extract_lin_basis",
    "SpecialFamDesc",
    "detect_diag_fam",
    "detect_pythag_fam",
    "detect_sum_fam2",
    "detect_two_cubes_family",
    "pythag_triple_form",
    "solve_binary_scan",
    "solve_diag_fam",
    "solve_int_fams",
    "solve_pythag_triples_fam",
    "solve_sum_of_squares_fam",
    "solve_two_cubes_family",
]
