# ruff: noqa: F403, F405
"""Explicit standard semialgebraic region families."""

from ._standard_regions_base import *
from ._standard_regions_composite import *
from ._standard_regions_curved import *
from ._standard_regions_polyhedral import *
from .boundary_topology import *

__all__ = [
    "Geometry",
    "StandardRegion",
    "Point",
    "AffineSpace",
    "Hyperplane",
    "HalfSpace",
    "AffineHalfSpace",
    "Line",
    "Ray",
    "Polytope",
    "TetrahedralComplex",
    "Zonotope",
    "Parallelogram",
    "Box",
    "Interval",
    "FinitePointSet",
    "Simplex",
    "Triangle",
    "Polygon",
    "RegularPolygon",
    "PolyhedralCone",
    "Parallelepiped",
    "Cube",
    "Tetrahedron",
    "Octahedron",
    "Icosahedron",
    "Dodecahedron",
    "Prism",
    "Pyramid",
    "Hexahedron",
    "Ball",
    "Sphere",
    "Circle",
    "Ellipsoid",
    "EllipsoidBoundary",
    "Cylinder",
    "Cone",
    "Torus",
    "FilledTorus",
    "SphericalShell",
    "Stadium",
    "Capsule",
    "ParametricRegion",
    "TransformedRegion",
    "BooleanRegion",
    "PolygonalComponent",
    "PolygonalSet",
    "PolyhedralShell",
    "PolyhedralComponent",
    "Polyhedron",
    "deduplicate_indexed_vertices",
    "polygon_vertices",
    "outer_polygons",
    "inner_polygons",
    "polyhedron_vertices",
    "polyhedron_face_indices",
    "outer_polyhedra",
    "inner_polyhedra",
    "is_standard_region",
]
