"""Generate the root-function documentation adequacy registry and report."""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import semialg  # noqa: E402

DOCS = ROOT / "docs"
MANIFEST = tomllib.loads((DOCS / "reference" / "primary_api_manifest.toml").read_text())["apis"]
COVERAGE = tomllib.loads((ROOT / "tests" / "public_api_coverage.toml").read_text())["apis"]

VERBS = re.compile(
    r"\b(return|compute|decide|construct|build|find|determine|integrate|solve|resolve|simplify|generate|convert|analyze|classify|prove|check|create|evaluate|apply|wrap|translate|scale|sample|plot|discretize|triangulate|implicitize|regularize|canonicalize|refine|subdivide|clip|count|partition|verify|test|project|decompose|replay)\b",
    re.I,
)


def fenced_code() -> str:
    blocks: list[str] = []
    for path in [ROOT / "README.md", *DOCS.rglob("*.md")]:
        text = path.read_text(encoding="utf-8")
        blocks.extend(
            m.group(1) for m in re.finditer(r"```(?:python|py)?\s*\n(.*?)```", text, re.S | re.I)
        )
    return "\n".join(blocks)


def mapped_section(name: str) -> str:
    target = MANIFEST[name]
    relative, anchor = target.split("#", 1)
    text = (DOCS / relative).read_text(encoding="utf-8")
    headings = list(re.finditer(r"^## (.+)$", text, re.M))
    for i, match in enumerate(headings):
        title = match.group(1).strip().lower()
        slug = re.sub(r"[^a-z0-9_ -]", "", title).replace(" ", "-")
        slug = re.sub(r"-+", "-", slug)
        if slug == anchor:
            end = headings[i + 1].start() if i + 1 < len(headings) else len(text)
            return text[match.start() : end]
    return ""


def parameter_names(obj) -> list[str]:
    return [p for p in inspect.signature(obj).parameters if p not in {"self", "cls"}]


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    code = fenced_code()
    rows = []
    for name in semialg.__all__:
        obj = getattr(semialg, name)
        if not inspect.isfunction(obj):
            continue
        doc = inspect.getdoc(obj) or ""
        section = mapped_section(name)
        page_rel = MANIFEST[name].split("#", 1)[0]
        page_text = (DOCS / page_rel).read_text(encoding="utf-8")
        params = parameter_names(obj)
        param_evidence = doc + "\n" + section
        dimensions = {
            "purpose": bool(doc and len(doc.splitlines()[0].strip()) >= 25),
            "signature": True,
            "parameters": all(
                re.search(rf"(?<![A-Za-z0-9_]){re.escape(p)}(?![A-Za-z0-9_])", param_evidence)
                for p in params
            ),
            "return_semantics": bool(VERBS.search(doc + "\n" + section)),
            "exactness": "**Exactness and certification.**" in page_text,
            "algorithm": "**Algorithm" in page_text,
            "limitations": "**Complexity and limitations.**" in page_text,
            "example": bool(re.search(rf"(?<![A-Za-z0-9_]){re.escape(name)}\s*\(", code)),
        }
        risk = COVERAGE[name]["risk"]
        required = ["purpose", "signature", "return_semantics", "exactness", "limitations"]
        if risk in {"high", "critical"}:
            required += ["parameters", "example"]
        if risk == "critical":
            required += ["algorithm"]
        missing = [d for d in required if not dimensions[d]]
        rows.append(
            (name, COVERAGE[name]["owner"], risk, dimensions, required, missing, MANIFEST[name])
        )

    out = [
        "# Generated by scripts/generate_root_api_documentation_adequacy.py; do not edit manually.",
        "schema_version = 1",
        "",
    ]
    for name, owner, risk, dims, required, missing, target in rows:
        out += [
            f"[functions.{toml_string(name)}]",
            f"owner = {toml_string(owner)}",
            f"risk = {toml_string(risk)}",
            f"reference = {toml_string(target)}",
            f"required = [{', '.join(toml_string(x) for x in required)}]",
            f"satisfied = [{', '.join(toml_string(k) for k, v in dims.items() if v)}]",
            f"missing = [{', '.join(toml_string(x) for x in missing)}]",
            f"status = {toml_string('adequate' if not missing else 'needs-deepening')}",
            "",
        ]
    (DOCS / "reference" / "root_function_documentation_adequacy.toml").write_text(
        "\n".join(out), encoding="utf-8"
    )

    adequate = sum(not r[5] for r in rows)
    by_dim = {
        d: sum(d in r[5] for r in rows)
        for d in [
            "purpose",
            "signature",
            "parameters",
            "return_semantics",
            "exactness",
            "algorithm",
            "limitations",
            "example",
        ]
    }
    report = [
        "# Root-function documentation adequacy",
        "",
        "This audit checks documentation *quality dimensions* for every root-level function, not merely whether the name appears in the reference index. It is generated from the live API, docstrings, the primary-reference manifest, and executable examples in fenced code blocks.",
        "",
        "The rubric deliberately distinguishes reference coverage from adequacy. Medium-risk functions require a clear purpose, inspectable signature, return semantics, and family-level exactness/limitations. High-risk functions additionally require parameter semantics and an executable-style documentation example. Critical functions additionally require algorithm/backend documentation.",
        "",
        f"**Current result:** {adequate}/{len(rows)} functions satisfy their risk-adjusted adequacy requirements; {len(rows) - adequate} need documentation deepening.",
        "",
        "## Gap summary",
        "",
        "| Dimension | Functions missing required evidence |",
        "|---|---:|",
    ]
    for d, n in by_dim.items():
        report.append(f"| `{d}` | {n} |")
    report += [
        "",
        "## Function-by-function audit",
        "",
        "| Function | Owner | Risk | Status | Missing dimensions | Reference |",
        "|---|---|---|---|---|---|",
    ]
    for name, owner, risk, _dims, _required, missing, target in rows:
        status = "adequate" if not missing else "needs deepening"
        gaps = ", ".join(f"`{x}`" for x in missing) or "—"
        rel, anchor = target.split("#", 1)
        report.append(
            f"| `{name}` | {owner} | {risk} | {status} | {gaps} | [{rel}](../{rel}#{anchor}) |"
        )
    report += [
        "",
        "## Interpretation",
        "",
        "A failing dimension is a concrete documentation task, not a claim that the implementation is defective. In particular, a family reference can accurately describe shared certification and complexity while a function still lacks parameter-specific guidance or a worked call. Conversely, adding prose merely to satisfy a counter is discouraged: examples should demonstrate a representative semantic distinction, and parameter text should explain non-obvious meaning rather than repeat the signature.",
        "",
        "The generated TOML registry is `docs/reference/root_function_documentation_adequacy.toml`. CI checks that it remains complete and reproducible as the root API changes.",
    ]
    (DOCS / "quality" / "root-api-documentation-adequacy.md").write_text(
        "\n".join(report) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
