"""Generate the complete root-API to substantive-documentation registry."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import semialg  # noqa: E402

DOCS = ROOT / "docs"
PAGES = [*sorted((DOCS / "reference").glob("*.md")), *sorted((DOCS / "guides").glob("*.md"))]


def slug(title: str) -> str:
    value = re.sub(r"[^a-z0-9_ -]", "", title.strip().lower()).replace(" ", "-")
    return re.sub(r"-+", "-", value)


def sections():
    for path in PAGES:
        text = path.read_text(encoding="utf-8")
        headings = list(re.finditer(r"^## (.+)$", text, re.M))
        for index, match in enumerate(headings):
            end = headings[index + 1].start() if index + 1 < len(headings) else len(text)
            yield path, slug(match.group(1)), match.group(1).strip(), text[match.start() : end]


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_manifest() -> str:
    all_sections = list(sections())
    rows: dict[str, str] = {}
    for name in semialg.__all__:
        if name == "__version__":
            rows[name] = "reference/package_metadata.md#primary-api-overview"
            continue
        pattern = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])")
        candidates = []
        for path, anchor, title, section in all_sections:
            if len(section.strip()) < 200 or not pattern.search(section):
                continue
            exact = slug(name) == anchor or title.strip("`") == name
            page_text = path.read_text(encoding="utf-8")
            family = "## Family contract" in page_text
            root_usage = path.name == "root_api_usage.md"
            priority = (
                0
                if exact and root_usage
                else 1
                if exact
                else 2
                if family
                else 3
                if root_usage
                else 4
            )
            candidates.append((priority, len(section), str(path.relative_to(DOCS)), anchor))
        if not candidates:
            raise ValueError(f"no substantive documentation section for public export {name!r}")
        _, _, relative, anchor = min(candidates)
        rows[name] = f"{relative}#{anchor}"
    lines = [
        "# Generated by scripts/generate_primary_api_manifest.py; do not edit manually.",
        "[apis]",
    ]
    for name in sorted(rows, key=lambda item: (item.lower(), item)):
        lines.append(f"{_toml_string(name)} = {_toml_string(rows[name])}")
    return "\n".join(lines) + "\n"


def main() -> None:
    (DOCS / "reference" / "primary_api_manifest.toml").write_text(
        render_manifest(), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
