"""Exact lattice and toric ideal algorithms over the integers."""

from __future__ import annotations

from collections.abc import Iterable, Sequence

import sympy as sp
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp


def _integer_matrix(matrix) -> sp.Matrix:
    mat = sp.Matrix(matrix)
    if mat.rows == 0 or mat.cols == 0:
        raise ValueError("matrix must have at least one row and one column")
    entries: list[int] = []
    for value in mat:
        item = sp.sympify(value)
        if item.is_Integer is not True:
            raise ValueError("matrix entries must be integers")
        entries.append(int(item))
    return sp.Matrix(mat.rows, mat.cols, entries)


def _variables(count: int, variables: Sequence[sp.Symbol] | None) -> tuple[sp.Symbol, ...]:
    if variables is None:
        return sp.symbols(f"x0:{count}")
    result = tuple(variables)
    if len(result) != count:
        raise ValueError("the number of variables must match the matrix width")
    if any(not isinstance(symbol, sp.Symbol) for symbol in result):
        raise TypeError("ideal variables must be SymPy symbols")
    if len(set(result)) != len(result):
        raise ValueError("ideal variables must be distinct")
    return result


def _canonical_move(move: Sequence[int]) -> tuple[int, ...]:
    values = tuple(int(value) for value in move)
    if not any(values):
        raise ValueError("a lattice move cannot be zero")
    first = next(value for value in values if value)
    if first < 0:
        values = tuple(-value for value in values)
    return values


def integer_kernel(matrix) -> tuple[tuple[int, ...], ...]:
    """Return a saturated integer basis for ``ker_Z(matrix)``.

    Smith normal form supplies unimodular column transformations, so the
    returned vectors form a genuine lattice basis rather than merely scaled
    rational-nullspace vectors.
    """
    mat = _integer_matrix(matrix)
    domain_matrix = DomainMatrix.from_Matrix(mat).convert_to(sp.ZZ)
    diagonal, _, right = smith_normal_decomp(domain_matrix)
    diagonal_matrix = diagonal.to_Matrix()
    rank = sum(diagonal_matrix[index, index] != 0 for index in range(min(diagonal_matrix.shape)))
    transform = right.to_Matrix()
    basis = []
    for column in range(rank, mat.cols):
        vector = tuple(int(transform[row, column]) for row in range(mat.cols))
        basis.append(_canonical_move(vector))
    return tuple(basis)


def binomial_from_move(move: Sequence[int], variables: Sequence[sp.Symbol]) -> sp.Expr:
    """Return ``x**move+ - x**move-`` for an integer lattice move."""
    values = tuple(int(value) for value in move)
    vars_ = tuple(variables)
    if len(values) != len(vars_):
        raise ValueError("move length must match the number of variables")
    if not any(values):
        raise ValueError("a lattice move cannot be zero")
    positive = sp.Integer(1)
    negative = sp.Integer(1)
    for symbol, exponent in zip(vars_, values, strict=True):
        if exponent > 0:
            positive *= symbol**exponent
        elif exponent < 0:
            negative *= symbol ** (-exponent)
    return sp.expand(positive - negative)


def binomial_ideal(
    moves: Iterable[Sequence[int]],
    variables: Sequence[sp.Symbol] | None = None,
) -> tuple[sp.Expr, ...]:
    """Return binomial generators associated with integer lattice moves."""
    move_list = tuple(tuple(int(value) for value in move) for move in moves)
    if not move_list:
        return tuple()
    width = len(move_list[0])
    if width == 0 or any(len(move) != width for move in move_list):
        raise ValueError("all lattice moves must have the same positive length")
    vars_ = _variables(width, variables)
    generators = {binomial_from_move(move, vars_) for move in move_list if any(move)}
    return tuple(sorted(generators, key=sp.default_sort_key))


def _eliminate(
    generators: Sequence[sp.Expr],
    eliminated: Sequence[sp.Symbol],
    variables: Sequence[sp.Symbol],
) -> tuple[sp.Expr, ...]:
    gb = sp.groebner(
        generators,
        *tuple(eliminated),
        *tuple(variables),
        order="lex",
        domain=sp.QQ,
    )
    hidden = set(eliminated)
    result = {
        sp.expand(poly.as_expr()) for poly in gb.polys if not (poly.as_expr().free_symbols & hidden)
    }
    return tuple(sorted(result, key=sp.default_sort_key))


def lattice_ideal(
    moves: Iterable[Sequence[int]],
    variables: Sequence[sp.Symbol] | None = None,
) -> tuple[sp.Expr, ...]:
    """Return the saturated lattice ideal generated by ``moves``.

    Saturation by the product of coordinates turns basis binomials into the
    full lattice ideal, independent of the chosen lattice basis.
    """
    move_list = tuple(tuple(int(value) for value in move) for move in moves)
    if not move_list:
        return tuple()
    width = len(move_list[0])
    vars_ = _variables(width, variables)
    generators = binomial_ideal(move_list, vars_)
    if not generators:
        return tuple()
    saturation_var = sp.Dummy("lattice_saturation")
    product = sp.prod(vars_)
    return _eliminate(
        (*generators, 1 - saturation_var * product),
        (saturation_var,),
        vars_,
    )


def toric_ideal(
    matrix,
    variables: Sequence[sp.Symbol] | None = None,
) -> tuple[sp.Expr, ...]:
    """Return the toric ideal of an integer exponent matrix.

    The computation eliminates a Laurent monomial parameterization. Inverse
    variables make the construction valid for arbitrary integer exponents,
    not only nonnegative matrices.
    """
    mat = _integer_matrix(matrix)
    vars_ = _variables(mat.cols, variables)
    params = sp.symbols(f"t0:{mat.rows}")
    inverses = sp.symbols(f"u0:{mat.rows}")
    relations: list[sp.Expr] = [params[row] * inverses[row] - 1 for row in range(mat.rows)]
    for column, variable in enumerate(vars_):
        monomial = sp.Integer(1)
        for row in range(mat.rows):
            exponent = int(mat[row, column])
            if exponent >= 0:
                monomial *= params[row] ** exponent
            else:
                monomial *= inverses[row] ** (-exponent)
        relations.append(variable - monomial)
    return _eliminate(relations, (*params, *inverses), vars_)


def _move_from_binomial(poly: sp.Expr, variables: tuple[sp.Symbol, ...]) -> tuple[int, ...]:
    polynomial = sp.Poly(poly, *variables, domain=sp.QQ)
    terms = polynomial.terms()
    if len(terms) != 2:
        raise ValueError("toric ideal generator is not binomial")
    (left_exp, left_coeff), (right_exp, right_coeff) = terms
    if left_coeff * right_coeff >= 0:
        raise ValueError("toric ideal generator does not have opposite-sign terms")
    move = tuple(a - b for a, b in zip(left_exp, right_exp, strict=True))
    return _canonical_move(move)


def markov_basis(matrix) -> tuple[tuple[int, ...], ...]:
    """Return an exact Markov basis for the integer design matrix.

    A binomial Gröbner generating set of the toric ideal is a Markov basis.
    The output consists of the corresponding exponent-difference moves.
    """
    mat = _integer_matrix(matrix)
    vars_ = _variables(mat.cols, None)
    generators = toric_ideal(mat, vars_)
    moves = {_move_from_binomial(poly, vars_) for poly in generators}
    return tuple(sorted(moves))


__all__ = [
    "binomial_from_move",
    "binomial_ideal",
    "integer_kernel",
    "lattice_ideal",
    "markov_basis",
    "toric_ideal",
]
